# Generated by Django 3.0.4 on 2020-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0004_auto_20200620_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='utype',
            field=models.IntegerField(max_length=10),
        ),
    ]
