# Generated by Django 3.0.4 on 2020-06-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0005_auto_20200620_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='utype',
        ),
    ]
