# Generated by Django 3.0.4 on 2020-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0006_remove_myuser_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='utype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
