# Generated by Django 3.0.4 on 2020-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0007_myuser_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='utype',
            field=models.IntegerField(null=True),
        ),
    ]
