# Generated by Django 3.0.4 on 2020-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0008_auto_20200620_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('minfo', models.CharField(default='', max_length=50, null=True)),
                ('mprice', models.IntegerField(default=0, null=True)),
                ('mqty', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
