# Generated by Django 3.0.4 on 2020-06-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0009_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, null=True)),
                ('lastAcess', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omqty', models.IntegerField(default=0, null=True)),
                ('omid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='omid', to='hmsmain.Medicine')),
                ('ooid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='hmsmain.Order')),
            ],
        ),
    ]
