# Generated by Django 3.0.4 on 2020-06-22 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0010_order_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastAcess',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
