# Generated by Django 3.0.4 on 2020-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0012_auto_20200622_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lastComment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
