# Generated by Django 3.0.4 on 2020-07-01 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsmain', '0014_consumption_consumptiondetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumptiondetail',
            old_name='coid',
            new_name='ccid',
        ),
    ]
